name:  tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.7.1