name: Web build & test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.2'
          channel: 'stable'
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter build web
      - run: flutter build linux
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/web/*"
          tag: WEBv1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}